const navItems=[['dashboard','fa-house','Dashboard'],['inventory','fa-boxes-stacked','Inventory'],['shopping','fa-cart-shopping','Shopping'],['analytics','fa-chart-line','Analytics'],['settings','fa-gear','Settings'],['notifications','fa-bell','Notifications'],['family','fa-users','Family']];
const state={view:'dashboard',dark:localStorage.getItem('theme')==='dark',products:[{id:1,name:'Milk',qty:1,unit:'L',category:'Groceries',price:4,threshold:2,expiry:'2026-06-01',location:'Fridge'},{id:2,name:'Dish Soap',qty:2,unit:'bottle',category:'Cleaning',price:6,threshold:1,expiry:'2027-01-01',location:'Kitchen'}],shopping:[{id:1,name:'Eggs',qty:1,price:5,purchased:false}],notes:[],notifications:[{id:1,msg:'Milk may run out in 2 days',read:false,prio:'high'},{id:2,msg:'Budget exceeded for snacks',read:false,prio:'med'}],family:[{name:'Alex',role:'Owner'},{name:'Jamie',role:'Member'}]};
let charts=[];
const $=s=>document.querySelector(s);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),1800)}
function setTheme(){document.documentElement.classList.toggle('dark',state.dark);localStorage.setItem('theme',state.dark?'dark':'light')}
function mountNav(){const mk=(m=false)=>navItems.map(([k,i,l])=>`<button data-v="${k}" class="nav-btn ${state.view===k?'active':''} ${m?'justify-center flex-col py-2 text-xs':''}"><i class="fa-solid ${i}"></i><span>${l}</span></button>`).join('');$('#sidebar-nav').innerHTML=mk();$('#mobile-nav').innerHTML=mk(true);document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{state.view=b.dataset.v;render();})}
function dashboard(){const low=state.products.filter(p=>p.qty<=p.threshold).length;return `<div class="grid md:grid-cols-4 gap-4 fade-in">${[['Total Items',state.products.length],['Low Stock',low],['Expiring',1],['Monthly Spend','$482']].map(k=>`<div class="card"><p class="text-sm text-slate-500">${k[0]}</p><p class="kpi">${k[1]}</p></div>`).join('')}</div><div class="grid lg:grid-cols-2 gap-4 mt-4"><div class="card"><canvas id="c1"></canvas></div><div class="card"><canvas id="c2"></canvas></div></div>`}
function inventory(){const rows=state.products.map(p=>`<tr class="border-b dark:border-slate-800"><td class="py-2">${p.name}</td><td>${p.qty} ${p.unit}</td><td>${p.category}</td><td><button onclick="adj(${p.id},1)">+</button> <button onclick="adj(${p.id},-1)">-</button> <button onclick="editP(${p.id})">Edit</button> <button onclick="delP(${p.id})">Delete</button></td></tr>`).join('');return `<div class="card"><div class="flex gap-2 mb-3"><input id="search" class="px-3 py-2 border rounded-xl w-full dark:bg-slate-800" placeholder="Search products" oninput="filterP(this.value)"><button onclick="openProductForm()" class="px-3 py-2 bg-indigo-600 text-white rounded-xl">Add Product</button></div><div class="overflow-auto"><table class="w-full text-sm"><thead><tr><th class="text-left">Name</th><th>Qty</th><th>Category</th><th>Actions</th></tr></thead><tbody id="inv-body">${rows||'<tr><td colspan=4 class="py-8 text-center">No products</td></tr>'}</tbody></table></div></div>`}
function shopping(){const items=state.shopping.map((s,i)=>`<div class="card flex justify-between items-center"><div><p class="font-medium ${s.purchased?'line-through opacity-60':''}">${s.name}</p><p class="text-sm">$${s.price}</p></div><div><button onclick="togShop(${s.id})">${s.purchased?'Undo':'Purchased'}</button> <button onclick="mv(${i},-1)">↑</button><button onclick="mv(${i},1)">↓</button></div></div>`).join(''); const total=state.shopping.filter(s=>!s.purchased).reduce((a,b)=>a+b.price,0);return `<div class="space-y-3">${items}<div class="card">Estimated: <b>$${total.toFixed(2)}</b></div><div class="card flex gap-2"><input id="sname" class="border rounded-xl px-3 py-2 flex-1 dark:bg-slate-800" placeholder="Add item"><input id="sprice" type="number" class="border rounded-xl px-3 py-2 w-28 dark:bg-slate-800" placeholder="Price"><button onclick="addShop()" class="px-3 py-2 bg-indigo-600 text-white rounded-xl">Add</button></div></div>`}
function notifications(){return `<div class="space-y-2">${state.notifications.map(n=>`<div class="card ${n.read?'opacity-60':''}"><p>${n.msg}</p><button onclick="readN(${n.id})" class="text-sm text-indigo-600">Mark read</button></div>`).join('')}</div>`}
function family(){return `<div class="grid lg:grid-cols-2 gap-4"><div class="card"><h3 class="font-semibold mb-2">Members</h3>${state.family.map(f=>`<div class="flex justify-between py-1"><span>${f.name}</span><span>${f.role}</span></div>`).join('')}<div class="mt-3 flex gap-2"><input id="fname" class="border rounded-xl px-3 py-2 flex-1 dark:bg-slate-800" placeholder="Invite member"><select id="frole" class="border rounded-xl px-3 py-2 dark:bg-slate-800"><option>Member</option><option>Owner</option></select><button onclick="addFam()" class="px-3 py-2 bg-indigo-600 text-white rounded-xl">Invite</button></div></div><div class="card"><h3 class="font-semibold">Activity Feed</h3><ul class="text-sm mt-2 list-disc pl-5"><li>Jamie updated inventory</li><li>Alex marked Eggs purchased</li></ul></div></div>`}
function analytics(){return `<div class="grid lg:grid-cols-3 gap-4"><div class="card lg:col-span-2"><canvas id="c3"></canvas></div><div class="card"><canvas id="c4"></canvas></div></div>`}
function settings(){return `<div class="space-y-3"><div class="card flex justify-between"><span>Dark mode</span><button onclick="state.dark=!state.dark;setTheme();render()" class="px-3 py-1 border rounded-lg">${state.dark?'On':'Off'}</button></div><div class="card">AI insight mode: <select class="ml-2 border rounded p-1 dark:bg-slate-800"><option>Balanced</option><option>Conservative</option><option>Aggressive</option></select></div><div class="card"><button onclick="toast('Backup completed')">Run backup simulation</button></div></div>`}
function render(){mountNav();$('#page-title').textContent=navItems.find(n=>n[0]===state.view)?.[2]||'Dashboard';const views={dashboard,inventory,shopping,analytics,settings,notifications,family};$('#view').innerHTML=views[state.view]?views[state.view]():dashboard();charts.forEach(c=>c.destroy());charts=[];if(state.view==='dashboard'){charts.push(new Chart(document.getElementById('c1'),{type:'doughnut',data:{labels:['Groceries','Cleaning','Medicine'],datasets:[{data:[40,25,35]}]}}));charts.push(new Chart(document.getElementById('c2'),{type:'line',data:{labels:['W1','W2','W3','W4'],datasets:[{label:'Spend',data:[90,120,80,140]}]}}));} if(state.view==='analytics'){charts.push(new Chart(document.getElementById('c3'),{type:'line',data:{labels:['Jan','Feb','Mar','Apr','May'],datasets:[{label:'Consumption',data:[210,240,230,280,300]}]}}));charts.push(new Chart(document.getElementById('c4'),{type:'pie',data:{labels:['Groceries','Utilities','Subscriptions'],datasets:[{data:[56,22,22]}]}}));}}
function openProductForm(p){const d=p||{};$('#modal').classList.remove('hidden');$('#modal').classList.add('flex');$('#modal-content').innerHTML=`<h3 class="text-xl font-semibold mb-3">${p?'Edit':'Add'} Product</h3><div class="grid gap-2"><input id="pn" class="border rounded-xl p-2 dark:bg-slate-800" placeholder="Product name" value="${d.name||''}"><input id="pq" type="number" class="border rounded-xl p-2 dark:bg-slate-800" placeholder="Quantity" value="${d.qty||1}"><input id="pc" class="border rounded-xl p-2 dark:bg-slate-800" placeholder="Category" value="${d.category||''}"><button onclick="saveP(${d.id||0})" class="bg-indigo-600 text-white rounded-xl py-2">Save</button><button onclick="closeM()">Cancel</button></div>`}
function closeM(){$('#modal').classList.add('hidden');$('#modal').classList.remove('flex')}
function saveP(id){const name=$('#pn').value.trim(),qty=Number($('#pq').value),cat=$('#pc').value.trim(); if(!name||qty<0||!cat) return toast('Please fill required fields'); if(id){const p=state.products.find(x=>x.id===id);Object.assign(p,{name,qty,category:cat});} else state.products.push({id:Date.now(),name,qty,unit:'unit',category:cat,price:0,threshold:1,expiry:'2026-12-31',location:'Pantry'}); closeM(); state.view='inventory'; render(); toast('Saved successfully')}
window.openProductForm=openProductForm; window.closeM=closeM;
window.adj=(id,v)=>{const p=state.products.find(x=>x.id===id); if(!p) return; p.qty=Math.max(0,p.qty+v); render();};
window.delP=(id)=>{state.products=state.products.filter(p=>p.id!==id); render(); toast('Deleted')};
window.editP=(id)=>openProductForm(state.products.find(p=>p.id===id));
window.filterP=(q)=>{const rows=state.products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())).map(p=>`<tr class='border-b dark:border-slate-800'><td class='py-2'>${p.name}</td><td>${p.qty} ${p.unit}</td><td>${p.category}</td><td><button onclick='adj(${p.id},1)'>+</button> <button onclick='adj(${p.id},-1)'>-</button> <button onclick='editP(${p.id})'>Edit</button> <button onclick='delP(${p.id})'>Delete</button></td></tr>`).join(''); document.getElementById('inv-body').innerHTML=rows||"<tr><td colspan=4 class='py-8 text-center'>No matches</td></tr>"}
window.togShop=(id)=>{const i=state.shopping.find(s=>s.id===id);i.purchased=!i.purchased;render()}; window.mv=(i,d)=>{const j=i+d;if(j<0||j>=state.shopping.length)return; [state.shopping[i],state.shopping[j]]=[state.shopping[j],state.shopping[i]];render()};
window.addShop=()=>{const n=$('#sname').value.trim(),p=Number($('#sprice').value); if(!n||!p) return toast('Enter name and price'); state.shopping.push({id:Date.now(),name:n,price:p,purchased:false}); render();};
window.readN=(id)=>{const n=state.notifications.find(n=>n.id===id);if(n)n.read=true;render()}; window.addFam=()=>{const n=$('#fname').value.trim(); if(!n) return toast('Enter a name'); state.family.push({name:n,role:$('#frole').value}); render(); toast('Invite sent')};
$('#auth-form').onsubmit=(e)=>{e.preventDefault(); $('#auth-screen').classList.add('hidden'); $('#main-shell').classList.remove('hidden'); render();}
$('#google-btn').onclick=()=>toast('Google auth simulated'); $('#theme-toggle').onclick=()=>{state.dark=!state.dark; setTheme(); render()}; $('#fab-add').onclick=()=>openProductForm(); setTheme();
